version: '3.8'
services:
  app:
    build: .
    container_name: vertical-text-detection
    ports:
      - "${PORT}:8000"
    env_file:
      - .env
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
    restart: unless-stopped
